title: "Hugo shortcodes and render hooks"
disableKinds: ["RSS", "taxonomy", "term"]

# Do not publish content in "_includes" directories as pages
cascade:
  build: { list: never, publishResources: false, render: never }
  _target: { path: "{,/**}/_includes{,/**}" }
